name: Backup Objects To Gdrive
on: [workflow_dispatch]
    
jobs:
  backup-to-grive:
    runs-on: ubuntu-latest
    steps:
        # Checkout the branch
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Backup with rclone
        run: |
          cat << EOF > ./rclone.conf
          ${{ secrets.OBJSTACK_RCLONE_CONF }}
          EOF
          sudo apt install -y rclone
          rclone --config rclone.conf lsd Gdrive-IILM:/Documents

          
